pub mod hexagonal;
pub mod clean;
pub mod onion;

pub use hexagonal::root::{hex_root_files, hex_root_folders};

use super::{FileStructure, FolderStructure};

// Readme
const README_FILE: &str = "README.md";
const README_CONTENT: &str = r#"
# Hexagonal Architecture Boilerplate

## Introduction

This is a boilerplate generated by Garch for a hexagonal architecture in Go.

## Getting Started

To get started, run the following command:

```bash
go run cmd/main.go
```

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

## Acknowledgments

- [Garch](https://github.com/Rhaqim/garch)
- [Hexagonal Architecture](https://en.wikipedia.org/wiki/Hexagonal_architecture_(software))
- [Go](https://golang.org/)
- [Rust](https://www.rust-lang.org/)
"#;

// License
const LICENSE_FILE: &str = "LICENSE";
const LICENSE_CONTENT: &str = r#"MIT License"#;

// Gitignore
const GITIGNORE_FILE: &str = ".gitignore";
const GITIGNORE_CONTENT: &str = r#"
# Binaries for programs and plugins
bin
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
go.work.sum

# Environment variables
*.env

# bundle
bundle

# ds store osx
.DS_Store
"#;

// Main File
const MAIN_FILE: &str = "main.go";
const MAIN_CONTENT: &str = r#"package main

import "fmt"

func main() {
    fmt.Println("Welcome to Garch!")
}
"#;

pub fn general_main_file() -> FileStructure {
    FileStructure {
        file_name: MAIN_FILE.to_string(),
        content: MAIN_CONTENT.to_string(),
    }
}

pub fn general_root_files() -> Vec<FileStructure> {
    vec![
        FileStructure {
            file_name: README_FILE.to_string(),
            content: README_CONTENT.to_string(),
        },
        FileStructure {
            file_name: LICENSE_FILE.to_string(),
            content: LICENSE_CONTENT.to_string(),
        },
        FileStructure {
            file_name: GITIGNORE_FILE.to_string(),
            content: GITIGNORE_CONTENT.to_string(),
        },
    ]
}

pub fn architecture_map() -> Vec<(&'static str, (Vec<FolderStructure>, Vec<FileStructure>))> {
    vec![
        ("hexagonal", (hex_root_folders(), hex_root_files())),
        ("clean", (vec![], vec![])),
        ("onion", (vec![], vec![])),
        ("layered", (vec![], vec![])),
    ]
}
